name: GoApp-CI
on:
  push:
    branches: ["master"]
env:
  IMAGE_NAME: libra
  REGISTRY: ghcr.io

jobs:
  code-security:
    name: Code Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

     # - name: Run gosec Security Scanner
     #   uses: securego/gosec@master
      #  with:
       #   args: ./...

  docker-build-and-scan:
    name: Docker Build and Security Scan
    needs: code-security
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "dvirmoyal25@gmail.com"
          git config --global user.name "dvir_moyal"

      - name: Install Commitizen
        run: |
          pip install commitizen

      - name: Bump version and create changelog
        id: bump
        run: |
          cz bump --yes
          VERSION=$(git describe --tags --abbrev=0)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Check Dockerfile Security
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning

      # Build but don't push yet (for security scanning)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image locally
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true # Load the image locally instead of pushing
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:latest

      # Scan the locally built image before pushing
      - name: Scan local Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          format: 'table'
          exit-code: '1' # Fail if vulnerabilities found
          severity: 'CRITICAL,HIGH'

      # Only push if security scan passes
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            **Docker Image:**
            - Name: `${{ env.IMAGE_NAME }}`
            - Tags:
              - `latest`
              - `${{ env.VERSION }}`
            
            **Security Scan Status:**
            - Code security scan completed
            - Dockerfile security scan completed
            - Container image scan completed and approved
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}